### ISSUE TITLE
Cannot add service from an image URL in latest Knative (0.8.1)

### ISSUE THREAD

**Issue by odockal** [talamer/vscode-knative#109]
1. Have all dependencies installed Yaml and (Kubernetes/Openshift), kn cli downloaded
2. Be connected/logged to the working cluster with installed components (serverless and knative components), have prepared project/namespace and folder is opened in vscode workspace
3. Open Knative View 
4. Assert: No service found, no error notification
5. Add new Server
6. Use http://quay.io/rhdevelopers/knative-tutorial-greeter:quarkus as image URL
7. Choose proper name, ie. `knativeservice`
8. Service is created
Actual result: No service is created, no notification appeared.. Just progress bar is still working...

**Comment by joshuawilson** [comment]
I just tried this. It works as expected. Can you confirm that you can create a service using the CLI.

**Comment by joshuawilson** [comment]
It appears that if you use `http://` in front of the image the creation of the Service hangs. That is a valid bug.

**Comment by joshuawilson** [comment]
And to make matters worse, the service does not appear in the list so you can not delete it to stop it from hanging.
You will need to run `kn service list` to get the name, then `kn service delete [NAME]` to clear it.

**Comment by odockal** [comment]
Yeah, copy paste the image location from slack obviously automatically adds http prefix... Thanks for looking at this.
