### ISSUE TITLE
Notification pop up for downloading kn cli sometimes does not appear

### ISSUE THREAD

**Issue by odockal** [talamer/vscode-knative#125]
It happen to me when debugging ui-tests and running extension from master locally. I noticed that two events occur after opening Knative activity Bar view. They are exclusive, so probably there is some bug in workflow. Let me explain. 
First one event: Displaying `Cannot find Knative CLI tool` notification
Second one: Showing tree of items (Brokers, Channels, Source, ...) under `eventing` view.

I noticed that when first one appears there is nothing under eventing view, just progress bar moving around. Although, when I get some items in eventing view then there is no notification... 

I was checking the codebase for showing notification (`cli-config.ts`) and since it occurs to me that this happens first I started to go through the code here.
I checked to have locally downloaded `kn` at `~/.vs-kn/kn`, and yet, it sometimes asks for downloading new `kn`. I will dig more...

**Comment by odockal** [comment]
Seems like even though it finds proper kn binary, the version is something that does not fulfill the condition and it tried to redownload it. Or maybe something else. Not really sure here.

**Comment by jeffmaury** [comment]
Go the same on Windows. I have a dialog that tells me that operator is not installed but when I click on the notification icon, I can see that CLI must be downloaded. Once CLI has been downloaded, Serving tree is populated. If I restart VSCode, then I need to redownload the CLI

**Comment by joshuawilson** [comment]
This is definitely a bug. It is sending false warnings.

I'm working on this now.

**Comment by joshuawilson** [comment]
This is the result of a race condition between multiple checks for the `kn` cli. To fix it, I moved the call out and up to be one of the first things done.

**Comment by joshuawilson** [comment]
@odockal Just to be clear. Were you seeing the `kn` download when you did NOT expect it? Or you did not get the download when you DID expect it. I'm confused by the title above.

I just fixed it so that it doesn't display a false warning about it not finding `kn` so you need to download it.

**Comment by odockal** [comment]
True that, it was downloading `kn` when it should not. (because there was already ~/.vs-kn/kn binary).

**Comment by joshuawilson** [comment]
OK, this should be fixed then. Closing this.
