### ISSUE TITLE
Severing tree not loads when service has a not-existing image

### ISSUE THREAD

**Issue by evidolob** [talamer/vscode-knative#133]
In case if some services existed with invalid image.
Try to create service with:
```bash
 kn service create s0 --image somethingNotExisting/helloworld
```
And open `Serving` tree, it continually shows loader on top, but none of tree item shown:
<img width="408" alt="Screenshot 2021-02-24 at 10 27 38" src="https://user-images.githubusercontent.com/929743/108971386-ed13e300-768a-11eb-966b-5de141b12729.png">

Found by @lstocchi  https://github.com/redhat-developer/intellij-knative/pull/7#discussion_r581261454

**Comment by joshuawilson** [comment]
I can reproduce this. It appears to not catch the error on `RevisionFailed`.

**Comment by joshuawilson** [comment]
Added a check for invalid image URLs. Display info to user and warnings.
