### ISSUE TITLE
Wrong error alert message

### ISSUE THREAD

**Issue by lstocchi** [talamer/vscode-knative#136]
My situation is this, I have the serving operator installed but i don't have the eventing.
When i open the extension this alert pop up but it tells me i miss the serving operator.
![image](https://user-images.githubusercontent.com/49404737/109801887-5f526d80-7c1f-11eb-8eab-22297ef75779.png)

If i execute the kn command
```
kn broker list
Error: no Knative eventing API found on the backend, please verify the installation
```
What really annoys me is the alert. Can't we add a node to the eventing tree with an error message? `No eventing operator installed` or something like that? The alert is really invasive for a message which is not vital. If i don't have the eventing operator i shouldn't be forced to install it.

**Comment by joshuawilson** [comment]
Added in #139
