### ISSUE TITLE
Display Traffic Splitting

### ISSUE THREAD

**Issue by joshuawilson** [talamer/vscode-knative#26]
# Description
As a user I want to be able to see the traffic splitting to the Service.

# Acceptance Criteria 
- It should display traffic splitting to each Revision in the Service that is getting the traffic.

**Comment by gorkem** [comment]
Can we use grayed-out icons for displaying revisions that are not receiving any traffic?
Latest revision should always be the first child element, under the `Service`. We can also add a "latest" on description in addition to the traffic weight.

**Comment by gorkem** [comment]
Also we need to display tags for a revisions of there are any.

**Comment by joshuawilson** [comment]
I agree. I do plan to fix the ordering. We also have #38 for filtering that is related. 

With the traffic displayed, unused and out of order would be very obvious and look odd.

I'm also trying to work out where/how to display the traffic with the intent that it would be updated.

**Comment by joshuawilson** [comment]
Traffic display has been merged. 
I'll leave this open until I can make issues for the other things commented here.

**Comment by joshuawilson** [comment]
I made #54 for displaying tags. I linked #47 for the icons. 
Closing this story.
