### ISSUE TITLE
Open in Browser is not working 

### ISSUE THREAD

**Issue by gorkem** [talamer/vscode-knative#36]
Fails with the following error. 

Unable to open 'knative-tutorial-greeter:quarkus': Unable to read file '/quay.io/rhdevelopers/knative-tutorial-greeter:quarkus' (Error: Unable to resolve non-existing file '/quay.io/rhdevelopers/knative-tutorial-greeter:quarkus').

**Comment by joshuawilson** [comment]
fixed in #37
