### ISSUE TITLE
Update Icons 

### ISSUE THREAD

**Issue by gorkem** [talamer/vscode-knative#47]
The current icon set looks like it has been cut from the sides. Can we use the icons from OpenShift console?

**Comment by joshuawilson** [comment]
I you referring to 3 letter icons like `SEV`? If so, they are text in OpenShift. So I made ones that fit the square dimensions. The first version matched exactly, but it wasn't readable or recognizable. 

I would prefer an actual icon instead of text.  If those are the icons you refer to then maybe I should talk to the PM about a new design.

**Comment by gorkem** [comment]
Tekton pipelines somehow uses them. Can you check what it did?

**Comment by joshuawilson** [comment]
In the DevConsole; 
- Pipelines get their "text" icons from https://github.com/openshift/console/blob/master/frontend/packages/dev-console/src/models/pipelines.ts#L12
- Knative get their "text" icons from https://github.com/openshift/console/blob/master/frontend/packages/knative-plugin/src/models.ts#L94

The icons in the tekton ext were created to look similar to DevConsole. They look to small to me, I think they are hard to read. So when I made the icons for knative, I made the text more readable. 

I did opt to square off the icon, as I thought it looked odd rounded. 

Is your concern that there is not enough space on the sides or that they aren't rounded? Or something else.

**Comment by gorkem** [comment]
I think Knative ones needs a bit margin on the sides. They are more readable than Tekton but then they feel like they were cut short and there is more of it

**Comment by joshuawilson** [comment]
I can make some adjustments.

**Comment by joshuawilson** [comment]
I'm going to add your request to change the revision icons when not active to this bug/task in the comments in Display Traffic Splitting #26

**Comment by joshuawilson** [comment]
All of the icons have been completely redrawn. Closing this.
