### ISSUE TITLE
Improve test coverage for utility classes

### ISSUE THREAD

**Issue by odockal** [talamer/vscode-knative#53]
Actually there is this test coverage stats:

File                     |  % Stmts | % Branch |  % Funcs |  % Lines |Uncovered Lines |
-------------------------|----------|----------|----------|----------|----------------|
 src/                    |    47.62 |        0 |    33.33 |       45 |                |
  extension.ts           |    47.62 |        0 |    33.33 |       45 |... 28,45,46,48 |
 src/kn/                 |    48.58 |    25.56 |       60 |    48.82 |                |
  config.ts              |    91.67 |      100 |    66.67 |    91.67 |             51 |
  kn-api.ts              |      100 |    92.86 |      100 |      100 |                |
  kn-cli-config.ts       |    25.29 |     5.26 |    16.67 |    25.29 |... 261,264,266 |
  knCli.ts               |       30 |       15 |       50 |       30 |... 108,110,111 |
  knExecute.ts           |    46.43 |     7.14 |       40 |    48.15 |... 34,36,38,39 |
 src/knative/            |    42.03 |       50 |    55.56 |    40.68 |                |
  knativeItem.ts         |      100 |      100 |      100 |      100 |                |
  knativeServices.ts     |    23.08 |       50 |    42.86 |    23.91 |... 127,130,132 |
  revision.ts            |      100 |      100 |      100 |      100 |                |
  service.ts             |      100 |      100 |      100 |      100 |                |
 src/output/             |    27.78 |        0 |       25 |    27.78 |                |
  knOutputChannel.ts     |    27.78 |        0 |       25 |    27.78 |... 54,55,57,58 |
 src/tree/               |    51.74 |    16.67 |    43.33 |    53.05 |                |
  knativeTreeItem.ts     |    43.18 |        0 |    45.45 |    43.18 |... 106,114,122 |
  serviceDataProvider.ts |    47.67 |    21.43 |       50 |    46.99 |... 252,257,258 |
  serviceExplorer.ts     |    69.05 |       50 |       20 |    78.38 |... 62,63,65,69 |
 src/util/               |    30.06 |     7.02 |    23.68 |    29.41 |                |
  download.ts            |    33.33 |        0 |        0 |    33.33 |... 27,28,30,33 |
  errorable.ts           |    71.43 |      100 |    33.33 |       60 |          33,38 |
  filters.ts             |       60 |        0 |        0 |       60 |          10,16 |
  parse.ts               |        0 |        0 |        0 |        0 |... 16,17,18,20 |
  platform.ts            |    81.82 |       50 |      100 |    81.82 |           9,32 |
  progress.ts            |        0 |        0 |        0 |        0 |... 72,73,79,80 |
  virtualfs.ts           |     25.4 |        0 |     6.25 |     25.4 |... 174,176,177 |
  watch.ts               |    44.44 |        0 |       50 |    44.44 |... 46,48,49,50 |
  windowUtils.ts         |       30 |        0 |        0 |       30 |... 32,33,36,43 |
-------------------------|----------|----------|----------|----------|----------------|
All files                |    43.31 |    18.09 |    42.28 |     43.3 |                |
-------------------------|----------|----------|----------|----------|----------------|

Issue aims to code under src/util.

**Comment by odockal** [comment]
After https://github.com/talamer/vscode-knative/commit/02fe65895172cbb26b7fac1509a5bf97a797d275 test coverage went to 59 percent.

**Comment by odockal** [comment]
@joshuawilson We could close this one or we need to cover more test cases for utility classes?

**Comment by joshuawilson** [comment]
if you don't think it needs anymore, I'll close it
