### ISSUE TITLE
Error if the connected cluster does not have knative 

### ISSUE THREAD

**Issue by gorkem** [talamer/vscode-knative#65]
I get the following error pop up when I connect to a cluster with no knative installed. The error should be handled better. Perhaps we can show a message on the tree view that states the `current user does not have access to knative resources`. 

```
undefinedservices.serving.knative.dev is forbidden: User "developer" cannot list resource "services" in API group "serving.knative.dev" in the namespace "namespace"
```

**Comment by jeffmaury** [comment]
The way we handled it in IJ Tekton is that we check that the Tekton Pipelines CRD is available on the cluster and if not it's reported to the user. If Tekton Triggers CRD is not available on the cluster, then Tekton Triggers related resources are not displayed in the tree.

**Comment by joshuawilson** [comment]
@jeffmaury are you using a CLI tool to check that? I do not think I can do that with the knative cli. I have a check in place but I haven't tested it against a user that doesn't have admin rights. The listed error says that it is for the `user "developer"`. Not sure if that is the or not yet.

**Comment by jeffmaury** [comment]
We're, using the fabric8 Java api but you can use kubectl api-resources
