### ISSUE TITLE
When user is not logged in to the current cluster extension shows 'undefinedUnauthorized' error message

### ISSUE THREAD

**Issue by dgolovin** [talamer/vscode-knative#68]
![image](https://user-images.githubusercontent.com/620330/85084878-edb6ba00-b18a-11ea-99d8-5c58d52f42c4.png)

Would be good to show item 'Please login to the cluster' to let user know what to do.

This is usually happening after starting cluster with CRC and then activating extension.

**Comment by joshuawilson** [comment]
I thought I had this fixed, I'll look into it.

**Comment by joshuawilson** [comment]
fixed
