### ISSUE TITLE
Error when `kn` is not installed.

### ISSUE THREAD

**Issue by joshuawilson** [talamer/vscode-knative#7]
It displays an error if it can't find the `kn` cli. I appears to also try to download it but that needs to be confirmed. 

error : `ENOENT: no such file or directory, chmod '/[PATH TO HOME]/.vs-kn/kn'`

**Comment by joshuawilson** [comment]
I think this is an async issue.

**Comment by gorkem** [comment]
It felt like it when I had the issue. I think it is trying to do chmod before download completes.

**Comment by joshuawilson** [comment]
I had to rewrite most of the download logic as there was a bug in how it was using Promises. 

It is fixed now.
