### ISSUE TITLE
Adding validation for Add service inputs

### ISSUE THREAD

**Issue by odockal** [talamer/vscode-knative#77]
One can easily pass adding new service with any string but no error nor validation pops up to correct user's behavior. Please add validation of passed values and/or add notification.

**Comment by joshuawilson** [comment]
I have added active validation of name duplication. However, validation of the image requires trying to use it. I have added post validation for the image. If a bad image string is used, there will be an error message that pops up. However, the Service is still created but now the user can see the issue and update the Service with a new image string. 

Closing this based on this fix. If you think there is a better way or something else is needed, please reopen this or open a new issue.
