### ISSUE TITLE
There is a slightly different behavior between how Kubernetes ext. and Knative ext. search for kubeconfig file

### ISSUE THREAD

**Issue by odockal** [talamer/vscode-knative#78]
Kubernetes extension can use Set Kubeconfig action to point at kubeconfig file but Knative does not then use it ( it does not khow to do that). It would be nice to have it documented that user have to set KUBECONFIG env. variable or put kubeconfig in ~/.kube folder (named `config`).

**Comment by odockal** [comment]
https://kubernetes.io/docs/concepts/configuration/organize-cluster-access-kubeconfig/

**Comment by joshuawilson** [comment]
This is in the README. Closing.
