### ISSUE TITLE
Error/failure report propagation into vscode-knative from cluster

### ISSUE THREAD

**Issue by odockal** [talamer/vscode-knative#79]
I was deploying (adding a service) from image but I used 'http://' prefix in image URL, while logged in openshift cluster one can spot an error coming from wrongly passed image URL (it wont let you pass image url with http procol prefixed when using openshift web console), nothing is shown in extension. It might be useful to propagate a status report or an error/failure in notification when something fails on cluster when deploying a service.

Think of this as suggestion, there is an issue opened for image url validation #77 which could also improve this state.

**Comment by joshuawilson** [comment]
The error returned is not specific to `http` but that it is not able to fetch the image. I have added a check for this and it displays to the user now. It also appears as a change in the name and the tooltip now.
